# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131317)
$foreground = rgb(F8CDBC)
$color0 = rgb(3B3A3F)
$color1 = rgb(0D0D1C)
$color2 = rgb(17111D)
$color3 = rgb(4A2823)
$color4 = rgb(70393A)
$color5 = rgb(88432A)
$color6 = rgb(B1552F)
$color7 = rgb(EDB097)
$color8 = rgb(A67B69)
$color9 = rgb(111125)
$color10 = rgb(1F1727)
$color11 = rgb(63352F)
$color12 = rgb(954C4D)
$color13 = rgb(B55938)
$color14 = rgb(EC713F)
$color15 = rgb(EDB097)
