# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E201E)
$foreground = rgb(D2D6CB)
$color0 = rgb(444645)
$color1 = rgb(121913)
$color2 = rgb(121A14)
$color3 = rgb(121A14)
$color4 = rgb(3A4434)
$color5 = rgb(5F674F)
$color6 = rgb(606851)
$color7 = rgb(B7BCAD)
$color8 = rgb(808479)
$color9 = rgb(18221A)
$color10 = rgb(18221A)
$color11 = rgb(18221A)
$color12 = rgb(4D5A45)
$color13 = rgb(7E896A)
$color14 = rgb(808B6B)
$color15 = rgb(B7BCAD)
