# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1E23)
$foreground = rgb(DEDCF3)
$color0 = rgb(454549)
$color1 = rgb(151626)
$color2 = rgb(292D6C)
$color3 = rgb(292D6C)
$color4 = rgb(474782)
$color5 = rgb(746FA2)
$color6 = rgb(7A74A6)
$color7 = rgb(C8C4E6)
$color8 = rgb(8C89A1)
$color9 = rgb(1C1D32)
$color10 = rgb(373C90)
$color11 = rgb(373C90)
$color12 = rgb(5F5FAD)
$color13 = rgb(9B94D8)
$color14 = rgb(A29ADD)
$color15 = rgb(C8C4E6)
