foreground   #ccc8e9
background   #010101
cursor       #ccc8e9

color0       #010101
color8       #8e8ca3
color1       #607dca
color9       #607dca
color2       #7c90d3
color10      #7c90d3
color3       #8f93d9
color11      #8f93d9
color4       #a39add
color12      #a39add
color5       #9c9cde
color13      #9c9cde
color6       #a79fdf
color14      #a79fdf
color7       #ccc8e9
color15      #ccc8e9
