# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8CDBC
background         #131317
cursor             #8C7271

active_tab_foreground     #131317
active_tab_background     #F8CDBC
inactive_tab_foreground   #F8CDBC
inactive_tab_background   #131317

active_border_color   #F8CDBC
inactive_border_color #131317
bell_border_color     #0D0D1C

color0      #3B3A3F
color1		#0D0D1C
color2		#17111D
color3		#4A2823
color4		#70393A
color5		#88432A
color6		#B1552F
color7		#EDB097
color8		#A67B69
color9		#111125
color10		#1F1727
color11		#63352F
color12		#954C4D
color13		#B55938
color14		#EC713F
color15		#EDB097
