# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D2D6CB
background         #1E201E
cursor             #757C73

active_tab_foreground     #1E201E
active_tab_background     #D2D6CB
inactive_tab_foreground   #D2D6CB
inactive_tab_background   #1E201E

active_border_color   #D2D6CB
inactive_border_color #1E201E
bell_border_color     #121913

color0      #444645
color1		#121913
color2		#121A14
color3		#121A14
color4		#3A4434
color5		#5F674F
color6		#606851
color7		#B7BCAD
color8		#808479
color9		#18221A
color10		#18221A
color11		#18221A
color12		#4D5A45
color13		#7E896A
color14		#808B6B
color15		#B7BCAD
