# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEDCF3
background         #1F1E23
cursor             #8B8CC2

active_tab_foreground     #1F1E23
active_tab_background     #DEDCF3
inactive_tab_foreground   #DEDCF3
inactive_tab_background   #1F1E23

active_border_color   #DEDCF3
inactive_border_color #1F1E23
bell_border_color     #151626

color0      #454549
color1		#151626
color2		#292D6C
color3		#292D6C
color4		#474782
color5		#746FA2
color6		#7A74A6
color7		#C8C4E6
color8		#8C89A1
color9		#1C1D32
color10		#373C90
color11		#373C90
color12		#5F5FAD
color13		#9B94D8
color14		#A29ADD
color15		#C8C4E6
