# Variables

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

windowrule = tag +social, match:class ^(discord|com.discordapp.Discord|Root)$


bind = SUPER ALT, 1, togglespecialworkspace, social

windowrule = workspace special:social silent, match:tag social*
